"""phase7_booking_orders

Revision ID: a566d875ea3b
Revises: 003_phase6_transport
Create Date: 2026-04-04 14:16:29.594372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a566d875ea3b'
down_revision: Union[str, Sequence[str], None] = '003_phase6_transport'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission_configs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fixed_fee', sa.Numeric(precision=18, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_configs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('pricing_mode', sa.String(length=20), server_default=sa.text("'formula'"), nullable=False),
    sa.Column('base_fare', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fare_per_km', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fare_per_min', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('min_fare', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('surge_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('surge_multiplier', sa.Numeric(precision=4, scale=2), server_default=sa.text('1.0'), nullable=True),
    sa.Column('quote_timeout_sec', sa.Integer(), server_default=sa.text('120'), nullable=True),
    sa.Column('accept_timeout_sec', sa.Integer(), server_default=sa.text('60'), nullable=True),
    sa.Column('min_quote', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('max_quote', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('driver_locations',
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('heading', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('speed_kmh', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('provider_id')
    )
    op.create_table('driver_availability_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'offline'"), nullable=False),
    sa.Column('online_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('offline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['provider_vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('service_category_id', sa.UUID(), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('pricing_mode', sa.String(length=20), server_default=sa.text("'formula'"), nullable=False),
    sa.Column('pickup_address', sa.Text(), nullable=False),
    sa.Column('pickup_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('pickup_lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('dropoff_address', sa.Text(), nullable=True),
    sa.Column('dropoff_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('dropoff_lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('route_id', sa.UUID(), nullable=True),
    sa.Column('schedule_id', sa.UUID(), nullable=True),
    sa.Column('rental_start_date', sa.Date(), nullable=True),
    sa.Column('rental_end_date', sa.Date(), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('estimated_fare', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('driver_quoted_fare', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('quote_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('customer_accepted_fare', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('final_fare', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('cancelled_by', sa.String(length=20), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('boarding_otp', sa.String(length=6), nullable=True),
    sa.Column('boarding_otp_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('boarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('driver_quoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('customer_decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('payment_status', sa.String(length=20), server_default=sa.text("'unpaid'"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['service_routes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['service_route_schedules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_category_id'], ['service_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['provider_vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_status_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # removed autogenerated index drops
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # removed autogenerated index creations
    op.drop_table('booking_status_logs')
    op.drop_table('bookings')
    op.drop_table('driver_availability_sessions')
    op.drop_table('driver_locations')
    op.drop_table('price_configs')
    op.drop_table('commission_configs')
    # ### end Alembic commands ###
